version: "3.8"

services:
  menu-meister-web:
    container_name: menu-meister-web
    build:
      context: web/
      dockerfile: Dockerfile
      target: prod
      args:
        - NEXT_PUBLIC_GRAPHQL_ENDPOINT=${NEXT_PUBLIC_GRAPHQL_ENDPOINT}
        - NEXT_PUBLIC_BRAND_NAME=${NEXT_PUBLIC_BRAND_NAME}
    restart: always
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.menu-meister-web.rule=Host(`menu-meister.coding.global`)'
      - 'traefik.http.routers.menu-meister-web.entrypoints=websecure'
      - 'traefik.http.routers.menu-meister-web.tls.certresolver=letsencrypt'
      - 'traefik.http.services.menu-meister-web.loadbalancer.server.port=3000'
  menu-meister-server:
    container_name: menu-meister-server
    build:
      context: server/
      dockerfile: Dockerfile
      target: prod
    restart: always
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}/${MYSQL_DB}
      - SECRET=${SECRET}
      - PORT=${PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
    depends_on:
      - menu-meister-db
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.menu-meister-server.rule=Host(`menu-meister.coding.global`) && PathPrefix(`/graphql`)'
      - 'traefik.http.routers.menu-meister-server.entrypoints=websecure'
      - 'traefik.http.routers.menu-meister-server.tls.certresolver=letsencrypt'
      - 'traefik.http.services.menu-meister-server.loadbalancer.server.port=4000'
  menu-meister-db:
    container_name: menu-meister-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    networks:
      - proxy

      
networks:
  proxy:
    external: false
    name: proxy
